services:
  # AFL++ without minimization
  afl-libtiff-quickmin:
    image: fuzz-libtiff-quickmin
    privileged: true
    container_name: "${COMPOSE_PROJECT_NAME:-default}-afl-libtiff-quickmin"
    environment:
      CORPUS_DIR: /corpus
      OUTPUT_DIR: /afl-output
      OUT: /out
      MINIMIZED_DIR: /corpus_min
      FUZZER_ID: master
      FUZZER_BIN: /out/tiffcp
    volumes:
      - ./corpus:/corpus:rw
      - ./corpus_min:/corpus_min:rw
    # entrypoint: ["/quick_minimize.sh"]
    tty: true
    stdin_open: true
    restart: "no"
volumes:
  # AFL output for minimized AFL run
  output-volume:
  # AFL output for unminimized AFL run
  unmin-output-volume:
  # Minimized corpus for minimized AFL run
  minimized-corpus-volume:
